export const REGIONS = [
  { id: 'north-america', label: 'North America' },
  { id: 'latin-america', label: 'Latin America' },
  { id: 'europe', label: 'Europe' },
  { id: 'middle-east', label: 'Middle East' },
  { id: 'africa', label: 'Africa' },
  { id: 'asia', label: 'Asia' },
  { id: 'oceania', label: 'Oceania' },
];

export const COUNTRY_REGIONS = {
  'US': 'north-america',
  'MX': 'north-america',
  'PR': 'north-america',
  'HN': 'north-america',
  'SV': 'north-america',
  'GT': 'north-america',
  'PA': 'north-america',
  'VE': 'latin-america',
  'CO': 'latin-america',
  'PE': 'latin-america',
  'AR': 'latin-america',
  'BR': 'latin-america',
  'BO': 'latin-america',
  'CL': 'latin-america',
  'HT': 'latin-america',
  'CU': 'latin-america',
  'PL': 'europe',
  'TR': 'europe',
  'HU': 'europe',
  'CZ': 'europe',
  'AT': 'europe',
  'SE': 'europe',
  'GB': 'europe',
  'FR': 'europe',
  'DE': 'europe',
  'IT': 'europe',
  'ES': 'europe',
  'RU': 'europe',
  'UA': 'europe',
  'PS': 'middle-east',
  'IL': 'middle-east',
  'LB': 'middle-east',
  'SY': 'middle-east',
  'IQ': 'middle-east',
  'YE': 'middle-east',
  'IR': 'middle-east',
  'JO': 'middle-east',
  'SA': 'middle-east',
  'QA': 'middle-east',
  'BH': 'middle-east',
  'AE': 'middle-east',
  'KW': 'middle-east',
  'EG': 'africa',
  'SD': 'africa',
  'SO': 'africa',
  'KE': 'africa',
  'UG': 'africa',
  'ET': 'africa',
  'NG': 'africa',
  'CD': 'africa',
  'ZA': 'africa',
  'CF': 'africa',
  'TD': 'africa',
  'NE': 'africa',
  'ML': 'africa',
  'BF': 'africa',
  'LY': 'africa',
  'DJ': 'africa',
  'TN': 'africa',
  'MR': 'africa',
  'CM': 'africa',
  'MZ': 'africa',
  'MM': 'asia',
  'TH': 'asia',
  'HK': 'asia',
  'PH': 'asia',
  'BD': 'asia',
  'ID': 'asia',
  'MY': 'asia',
  'SG': 'asia',
  'VN': 'asia',
  'TW': 'asia',
  'JP': 'asia',
  'KR': 'asia',
  'CN': 'asia',
  'PK': 'asia',
  'IN': 'asia',
  'AF': 'asia',
  'FJ': 'oceania',
};

export function getRegion(countryCode) {
  return COUNTRY_REGIONS[countryCode] || null;
}
